include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.mocks.dart"
    - "messages_*.dart"
  errors:
    avoid_single_cascade_in_expression_statements: ignore
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    non_constant_identifier_names: ignore
    sort_pub_dependencies: ignore
