name: masjid_enroute
description: Find masjids along your route.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.3
  flutter_config: ^2.0.0
  flutter_hooks: ^0.17.0
  flutter_polyline_points: ^1.0.0
  freezed_annotation: ^0.14.2
  geocoding: ^2.0.0
  geolocator: ^7.2.0+1
  google_maps_flutter: ^2.0.6
  google_place: ^0.4.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hooks_riverpod: ^0.14.0+4
  json_annotation: ^4.0.1
  map_launcher: ^2.1.1
  modal_bottom_sheet: ^2.0.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.0.5
  dependency_validator: ^3.1.0
  flutter_gen_runner: ^3.1.1
  flutter_launcher_icons: ^0.9.0
  freezed: ^0.14.2
  hive_generator: ^1.1.0
  json_serializable: ^4.1.3
  lint: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/homescreen.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#0072CE"

flutter_gen: null
